package com.lapissea.dfs.tools.newlogger.display.vk.enums;

import com.lapissea.dfs.tools.newlogger.display.VUtils;
import com.lapissea.dfs.tools.newlogger.display.vk.Flags;

import static org.lwjgl.vulkan.EXTAttachmentFeedbackLoopLayout.VK_IMAGE_USAGE_ATTACHMENT_FEEDBACK_LOOP_BIT_EXT;
import static org.lwjgl.vulkan.EXTFragmentDensityMap.VK_IMAGE_USAGE_FRAGMENT_DENSITY_MAP_BIT_EXT;
import static org.lwjgl.vulkan.HUAWEIInvocationMask.VK_IMAGE_USAGE_INVOCATION_MASK_BIT_HUAWEI;
import static org.lwjgl.vulkan.KHRFragmentShadingRate.VK_IMAGE_USAGE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR;
import static org.lwjgl.vulkan.KHRVideoDecodeQueue.VK_IMAGE_USAGE_VIDEO_DECODE_DPB_BIT_KHR;
import static org.lwjgl.vulkan.KHRVideoDecodeQueue.VK_IMAGE_USAGE_VIDEO_DECODE_DST_BIT_KHR;
import static org.lwjgl.vulkan.KHRVideoDecodeQueue.VK_IMAGE_USAGE_VIDEO_DECODE_SRC_BIT_KHR;
import static org.lwjgl.vulkan.KHRVideoEncodeQuantizationMap.VK_IMAGE_USAGE_VIDEO_ENCODE_EMPHASIS_MAP_BIT_KHR;
import static org.lwjgl.vulkan.KHRVideoEncodeQuantizationMap.VK_IMAGE_USAGE_VIDEO_ENCODE_QUANTIZATION_DELTA_MAP_BIT_KHR;
import static org.lwjgl.vulkan.KHRVideoEncodeQueue.VK_IMAGE_USAGE_VIDEO_ENCODE_DPB_BIT_KHR;
import static org.lwjgl.vulkan.KHRVideoEncodeQueue.VK_IMAGE_USAGE_VIDEO_ENCODE_DST_BIT_KHR;
import static org.lwjgl.vulkan.KHRVideoEncodeQueue.VK_IMAGE_USAGE_VIDEO_ENCODE_SRC_BIT_KHR;
import static org.lwjgl.vulkan.QCOMImageProcessing.VK_IMAGE_USAGE_SAMPLE_BLOCK_MATCH_BIT_QCOM;
import static org.lwjgl.vulkan.QCOMImageProcessing.VK_IMAGE_USAGE_SAMPLE_WEIGHT_BIT_QCOM;
import static org.lwjgl.vulkan.VK10.*;
import static org.lwjgl.vulkan.VK14.VK_IMAGE_USAGE_HOST_TRANSFER_BIT;

public enum VkImageUsageFlag implements VUtils.FlagSetValue{
	
	TRANSFER_SRC(VK_IMAGE_USAGE_TRANSFER_SRC_BIT),
	TRANSFER_DST(VK_IMAGE_USAGE_TRANSFER_DST_BIT),
	SAMPLED(VK_IMAGE_USAGE_SAMPLED_BIT),
	STORAGE(VK_IMAGE_USAGE_STORAGE_BIT),
	COLOR_ATTACHMENT(VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT),
	DEPTH_STENCIL_ATTACHMENT(VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT),
	TRANSIENT_ATTACHMENT(VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT),
	INPUT_ATTACHMENT(VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT),
	HOST_TRANSFER(VK_IMAGE_USAGE_HOST_TRANSFER_BIT),
	VIDEO_DECODE_DST_KHR(VK_IMAGE_USAGE_VIDEO_DECODE_DST_BIT_KHR),
	VIDEO_DECODE_SRC_KHR(VK_IMAGE_USAGE_VIDEO_DECODE_SRC_BIT_KHR),
	VIDEO_DECODE_DPB_KHR(VK_IMAGE_USAGE_VIDEO_DECODE_DPB_BIT_KHR),
	FRAGMENT_DENSITY_MAP_EXT(VK_IMAGE_USAGE_FRAGMENT_DENSITY_MAP_BIT_EXT),
	FRAGMENT_SHADING_RATE_ATTACHMENT_KHR(VK_IMAGE_USAGE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR),
	VIDEO_ENCODE_DST_KHR(VK_IMAGE_USAGE_VIDEO_ENCODE_DST_BIT_KHR),
	VIDEO_ENCODE_SRC_KHR(VK_IMAGE_USAGE_VIDEO_ENCODE_SRC_BIT_KHR),
	VIDEO_ENCODE_DPB_KHR(VK_IMAGE_USAGE_VIDEO_ENCODE_DPB_BIT_KHR),
	ATTACHMENT_FEEDBACK_LOOP_EXT(VK_IMAGE_USAGE_ATTACHMENT_FEEDBACK_LOOP_BIT_EXT),
	INVOCATION_MASK_HUAWEI(VK_IMAGE_USAGE_INVOCATION_MASK_BIT_HUAWEI),
	SAMPLE_WEIGHT_QCOM(VK_IMAGE_USAGE_SAMPLE_WEIGHT_BIT_QCOM),
	SAMPLE_BLOCK_MATCH_QCOM(VK_IMAGE_USAGE_SAMPLE_BLOCK_MATCH_BIT_QCOM),
	VIDEO_ENCODE_QUANTIZATION_DELTA_MAP_KHR(VK_IMAGE_USAGE_VIDEO_ENCODE_QUANTIZATION_DELTA_MAP_BIT_KHR),
	VIDEO_ENCODE_EMPHASIS_MAP_KHR(VK_IMAGE_USAGE_VIDEO_ENCODE_EMPHASIS_MAP_BIT_KHR),
	;
	
	public final int bit;
	VkImageUsageFlag(int bit){ this.bit = bit; }
	
	@Override
	public int bit(){ return bit; }
	
	public static Flags<VkImageUsageFlag> from(int props){ return new Flags<>(VkImageUsageFlag.class, props); }
}
