package com.lapissea.dfs.tools.newlogger.display.vk.enums;

import com.lapissea.dfs.utils.iterableplus.Iters;
import org.lwjgl.vulkan.EXTDebugReport;
import org.lwjgl.vulkan.EXTFullScreenExclusive;
import org.lwjgl.vulkan.EXTImageCompressionControl;
import org.lwjgl.vulkan.EXTImageDrmFormatModifier;
import org.lwjgl.vulkan.EXTShaderObject;
import org.lwjgl.vulkan.KHRDeferredHostOperations;
import org.lwjgl.vulkan.KHRDisplaySwapchain;
import org.lwjgl.vulkan.KHRPipelineBinary;
import org.lwjgl.vulkan.KHRSurface;
import org.lwjgl.vulkan.KHRSwapchain;
import org.lwjgl.vulkan.KHRVideoEncodeQueue;
import org.lwjgl.vulkan.KHRVideoQueue;
import org.lwjgl.vulkan.NVGLSLShader;
import org.lwjgl.vulkan.VK10;
import org.lwjgl.vulkan.VK11;
import org.lwjgl.vulkan.VK12;
import org.lwjgl.vulkan.VK13;
import org.lwjgl.vulkan.VK14;

import java.util.Map;

public enum VkResult{
	SUCCESS(VK10.VK_SUCCESS),
	NOT_READY(VK10.VK_NOT_READY),
	TIMEOUT(VK10.VK_TIMEOUT),
	EVENT_SET(VK10.VK_EVENT_SET),
	EVENT_RESET(VK10.VK_EVENT_RESET),
	INCOMPLETE(VK10.VK_INCOMPLETE),
	ERROR_OUT_OF_HOST_MEMORY(VK10.VK_ERROR_OUT_OF_HOST_MEMORY),
	ERROR_OUT_OF_DEVICE_MEMORY(VK10.VK_ERROR_OUT_OF_DEVICE_MEMORY),
	ERROR_INITIALIZATION_FAILED(VK10.VK_ERROR_INITIALIZATION_FAILED),
	ERROR_DEVICE_LOST(VK10.VK_ERROR_DEVICE_LOST),
	ERROR_MEMORY_MAP_FAILED(VK10.VK_ERROR_MEMORY_MAP_FAILED),
	ERROR_LAYER_NOT_PRESENT(VK10.VK_ERROR_LAYER_NOT_PRESENT),
	ERROR_EXTENSION_NOT_PRESENT(VK10.VK_ERROR_EXTENSION_NOT_PRESENT),
	ERROR_FEATURE_NOT_PRESENT(VK10.VK_ERROR_FEATURE_NOT_PRESENT),
	ERROR_INCOMPATIBLE_DRIVER(VK10.VK_ERROR_INCOMPATIBLE_DRIVER),
	ERROR_TOO_MANY_OBJECTS(VK10.VK_ERROR_TOO_MANY_OBJECTS),
	ERROR_FORMAT_NOT_SUPPORTED(VK10.VK_ERROR_FORMAT_NOT_SUPPORTED),
	ERROR_FRAGMENTED_POOL(VK10.VK_ERROR_FRAGMENTED_POOL),
	ERROR_UNKNOWN(VK10.VK_ERROR_UNKNOWN),
	ERROR_OUT_OF_POOL_MEMORY(VK11.VK_ERROR_OUT_OF_POOL_MEMORY),
	ERROR_INVALID_EXTERNAL_HANDLE(VK11.VK_ERROR_INVALID_EXTERNAL_HANDLE),
	ERROR_FRAGMENTATION(VK12.VK_ERROR_FRAGMENTATION),
	ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS(VK12.VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS),
	PIPELINE_COMPILE_REQUIRED(VK13.VK_PIPELINE_COMPILE_REQUIRED),
	ERROR_NOT_PERMITTED(VK14.VK_ERROR_NOT_PERMITTED),
	ERROR_SURFACE_LOST_KHR(KHRSurface.VK_ERROR_SURFACE_LOST_KHR),
	ERROR_NATIVE_WINDOW_IN_USE_KHR(KHRSurface.VK_ERROR_NATIVE_WINDOW_IN_USE_KHR),
	SUBOPTIMAL_KHR(KHRSwapchain.VK_SUBOPTIMAL_KHR),
	ERROR_OUT_OF_DATE_KHR(KHRSwapchain.VK_ERROR_OUT_OF_DATE_KHR),
	ERROR_INCOMPATIBLE_DISPLAY_KHR(KHRDisplaySwapchain.VK_ERROR_INCOMPATIBLE_DISPLAY_KHR),
	ERROR_VALIDATION_FAILED_EXT(EXTDebugReport.VK_ERROR_VALIDATION_FAILED_EXT),
	ERROR_INVALID_SHADER_NV(NVGLSLShader.VK_ERROR_INVALID_SHADER_NV),
	ERROR_IMAGE_USAGE_NOT_SUPPORTED_KHR(KHRVideoQueue.VK_ERROR_IMAGE_USAGE_NOT_SUPPORTED_KHR),
	ERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHR(KHRVideoQueue.VK_ERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHR),
	ERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHR(KHRVideoQueue.VK_ERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHR),
	ERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHR(KHRVideoQueue.VK_ERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHR),
	ERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHR(KHRVideoQueue.VK_ERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHR),
	ERROR_VIDEO_STD_VERSION_NOT_SUPPORTED_KHR(KHRVideoQueue.VK_ERROR_VIDEO_STD_VERSION_NOT_SUPPORTED_KHR),
	ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT(EXTImageDrmFormatModifier.VK_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT),
	ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT(EXTFullScreenExclusive.VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT),
	THREAD_IDLE_KHR(KHRDeferredHostOperations.VK_THREAD_IDLE_KHR),
	THREAD_DONE_KHR(KHRDeferredHostOperations.VK_THREAD_DONE_KHR),
	OPERATION_DEFERRED_KHR(KHRDeferredHostOperations.VK_OPERATION_DEFERRED_KHR),
	OPERATION_NOT_DEFERRED_KHR(KHRDeferredHostOperations.VK_OPERATION_NOT_DEFERRED_KHR),
	ERROR_INVALID_VIDEO_STD_PARAMETERS_KHR(KHRVideoEncodeQueue.VK_ERROR_INVALID_VIDEO_STD_PARAMETERS_KHR),
	ERROR_COMPRESSION_EXHAUSTED_EXT(EXTImageCompressionControl.VK_ERROR_COMPRESSION_EXHAUSTED_EXT),
	INCOMPATIBLE_SHADER_BINARY_EXT(EXTShaderObject.VK_INCOMPATIBLE_SHADER_BINARY_EXT),
	PIPELINE_BINARY_MISSING_KHR(KHRPipelineBinary.VK_PIPELINE_BINARY_MISSING_KHR),
	ERROR_NOT_ENOUGH_SPACE_KHR(KHRPipelineBinary.VK_ERROR_NOT_ENOUGH_SPACE_KHR),
	;
	
	public final int id;
	VkResult(int id){ this.id = id; }
	
	private static final Map<Integer, VkResult> BY_ID = Iters.from(VkResult.class).toMap(e -> e.id, e -> e);
	
	public static VkResult from(int id){
		var value = BY_ID.get(id);
		if(value == null){
			throw new IllegalArgumentException("Unknown id: " + id);
		}
		return value;
	}
	
}
