package com.lapissea.jorth.repro;

import com.lapissea.jorth.ClassDefinition;
import com.lapissea.jorth.FunctionDefinition;
import com.lapissea.jorth.exceptions.MalformedJorth;
import com.lapissea.jorth.lang.ClassName;
import com.lapissea.util.function.UnsafeConsumer;
import org.testng.annotations.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * BUG-37 (jorth-sipush): silent int constant corruption in generated bytecode.
 *
 * What the code is supposed to do:
 *   Pushing an int constant (CodeBlock.val(int) -> Insn.IVal, or Insn.Increment for
 *   "add(int)") must emit a JVM instruction that loads EXACTLY the requested int:
 *   ICONST_0..ICONST_5 for 0..5, otherwise BIPUSH/SIPUSH/LDC chosen by value range,
 *   so that any int in [-2^31, 2^31) round-trips correctly.
 *
 * What it actually does:
 *   Insn.IVal.emit (Jorth/src/main/java/com/lapissea/jorth/Insn.java:58-68) emits
 *   SIPUSH for EVERY int outside 0..5, with no range check. SIPUSH encodes only 16
 *   signed bits, so the value is silently truncated to `value & 0xFFFF`:
 *     - val(70000)  loads 4464   (70000 & 0xFFFF)
 *     - val(40000)  loads -25536 (40000 & 0xFFFF, re-signed)
 *   ASM does not validate the operand range, and the JVM verifier accepts any
 *   SIPUSH operand, so the class loads fine and the corrupted value is returned
 *   silently. Insn.Increment's INT case (Insn.java:920) calls IVal.emit with the
 *   increment amount, so .add(int) is affected the same way. LVal (Insn.java:81-87)
 *   is correct because it uses LDC for values outside 0..1.
 *
 * Why the test fails:
 *   The generated methods load the truncated constants, so asserting the true value
 *   fails with the masked value (e.g. "expected: 70000 but was: 4464"), demonstrating
 *   the silent constant corruption. The in-range test (SIPUSH legal domain) passes,
 *   isolating the failure to out-of-range values.
 */
public class ReproJorthSipushTests{
	
	private static Class<?> generateAndLoad(String className, UnsafeConsumer<ClassDefinition, MalformedJorth> generator) throws Exception{
		ClassDefinition cd = new ClassDefinition(null);
		cd.name(ClassName.dotted(className));
		generator.accept(cd);
		byte[] bytes = cd.getClassFile();
		var loader = new ClassLoader(ReproJorthSipushTests.class.getClassLoader()){
			@Override
			protected Class<?> findClass(String name) throws ClassNotFoundException{
				if(name.equals(className)){
					return defineClass(name, bytes, 0, bytes.length);
				}
				return super.findClass(name);
			}
		};
		return Class.forName(className, true, loader);
	}
	
	@Test
	void valuesInSipushRangeAreCorrect() throws Exception{
		// Control: 0..5 use ICONST_n, -32768..32767 are legal SIPUSH values.
		// These must all pass, proving the harness is sound and only out-of-range
		// constants are corrupted.
		var cls = generateAndLoad("test.CL_sipushInRange", cd -> {
			for(int v : new int[]{0, 5, 100, 32767, -32768, -30000}){
				FunctionDefinition fn = cd.function("v" + v).staticAcc().returns(int.class);
				fn.body().val(v).returnOp();
			}
		});
		for(int v : new int[]{0, 5, 100, 32767, -32768, -30000}){
			assertThat(cls.getMethod("v" + v).invoke(null))
			    .as("constant in SIPUSH range %d must round-trip", v)
			    .isEqualTo(v);
		}
	}
	
	@Test
	void valuesOutOfRangeOfSipushAreCorrupted() throws Exception{
		// 70000 and 40000 do NOT fit in a signed 16-bit value. IVal.emit
		// (Insn.java:66) still emits SIPUSH, so the loaded values are
		// 70000 & 0xFFFF = 4464 and 40000 & 0xFFFF = -25536.
		var cls = generateAndLoad("test.CL_sipushOutOfRange", cd -> {
			for(int v : new int[]{70000, 40000}){
				FunctionDefinition fn = cd.function("v" + v).staticAcc().returns(int.class);
				fn.body().val(v).returnOp();
			}
		});
		// Bug: expected 70000, but the emitted SIPUSH truncated it to 4464.
		assertThat(cls.getMethod("v70000").invoke(null))
		    .as("val(70000) must load 70000; SIPUSH truncation yields 70000 & 0xFFFF = 4464")
		    .isEqualTo(70000);
		// Bug: expected 40000, but the emitted SIPUSH truncated+re-signed it to -25536.
		assertThat(cls.getMethod("v40000").invoke(null))
		    .as("val(40000) must load 40000; SIPUSH truncation yields 40000 & 0xFFFF = -25536")
		    .isEqualTo(40000);
	}
	
	@Test
	void incrementIntUsesSameTruncatingPath() throws Exception{
		// Insn.Increment INT case (Insn.java:918-922) pushes the increment via
		// IVal.emit(writer, val) -> same SIPUSH-for-everything bug.
		var cls = generateAndLoad("test.CL_sipushIncrement", cd -> {
			FunctionDefinition fn = cd.function("add70000").staticAcc()
			                            .arg(int.class, "x")
			                            .returns(int.class);
			fn.body()
			  .get("x")
			  .add(70000)   // Increment(INT) emits IVal(70000) -> SIPUSH(70000) -> 4464
			  .returnOp();
		});
		// Bug: x + 70000 is computed as x + 4464 because the constant was truncated.
		assertThat(cls.getMethod("add70000", int.class).invoke(null, 0))
		    .as("0 + 70000 must be 70000; truncated constant yields 4464")
		    .isEqualTo(70000);
	}
}
