package com.lapissea.jorth.repro;

import com.lapissea.jorth.ClassDefinition;
import com.lapissea.jorth.FunctionDefinition;
import com.lapissea.jorth.exceptions.MalformedJorth;
import com.lapissea.jorth.lang.ClassName;
import com.lapissea.util.function.UnsafeConsumer;
import org.testng.annotations.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * JORTH-B07: silent long constant corruption in generated bytecode.
 *
 * What the code is supposed to do:
 *   Pushing a long constant (CodeBlock.val(long) -> Insn.LVal, or the Insn.Increment
 *   LONG case for long addition) must emit a JVM instruction that loads EXACTLY the
 *   requested long: LCONST_0/LCONST_1 for 0L/1L, otherwise LDC, so that any long in
 *   the full 64-bit range round-trips correctly.
 *
 * What it actually does:
 *   Insn.LVal.emit (Jorth/src/main/java/com/lapissea/jorth/Insn.java:81-87) does
 *   `switch((int)value)` - i.e. it only tests the LOW 32 BITS of the long:
 *     case 0 -> LCONST_0
 *     case 1 -> LCONST_1
 *     default -> visitLdcInsn(value)
 *   So ANY long whose low 32 bits are 0 or 1 but which is NOT 0L/1L is silently
 *   emitted as LCONST_0/LCONST_1 and the value is corrupted:
 *     - val(4294967296L)  (2^32, low 32 bits == 0) loads 0L
 *     - val(-4294967295L) (low 32 bits == 1)       loads 1L
 *   ASM does not validate the emitted instruction and the JVM verifier accepts the
 *   class (both LCONST_n and LDC push a long), so the class loads fine and the
 *   corrupted value is returned silently. Insn.Increment's LONG case
 *   (Insn.java:923-926) calls LVal.emit(writer, val.longValue()) before LADD, so
 *   long addition routes through the same corrupting emitter.
 *
 * Why the tests fail:
 *   The generated methods load the corrupted constants, so asserting the true value
 *   fails with the masked value (e.g. "expected: 4294967296 but was: 0"),
 *   demonstrating the silent constant corruption. The control tests (a value whose
 *   low 32 bits are not 0/1, and the intended 0L/1L LCONST cases) pass against the
 *   current code, isolating the failure to the low-32-bits 0/1 case and proving the
 *   harness and the LDC path are sound.
 */
public class ReproJorthLValTests{
	
	private static Class<?> generateAndLoad(String className, UnsafeConsumer<ClassDefinition, MalformedJorth> generator) throws Exception{
		ClassDefinition cd = new ClassDefinition(null);
		cd.name(ClassName.dotted(className));
		generator.accept(cd);
		byte[] bytes = cd.getClassFile();
		var loader = new ClassLoader(ReproJorthLValTests.class.getClassLoader()){
			@Override
			protected Class<?> findClass(String name) throws ClassNotFoundException{
				if(name.equals(className)){
					return defineClass(name, bytes, 0, bytes.length);
				}
				return super.findClass(name);
			}
		};
		return Class.forName(className, true, loader);
	}
	
	@Test
	void longValLow32BitsZeroIsCorrupted() throws Exception{
		// 4294967296L == 2^32 has low 32 bits == 0, but it is NOT 0L.
		// LVal.emit (Insn.java:82) switches on (int)value, matches case 0 and
		// emits LCONST_0, so the generated method returns 0L instead of 2^32.
		var cls = generateAndLoad("reprolval.LValLow32Zero", cd -> {
			FunctionDefinition fn = cd.function("v2to32").staticAcc().returns(long.class);
			fn.body()
			  .val(4294967296L) // LVal(4294967296L) -> emit: (int)value == 0 -> LCONST_0 (bug; must be LDC 4294967296L)
			  .returnOp();
		});
		// Bug: expected 4294967296, but the emitted LCONST_0 makes the method return 0.
		assertThat(cls.getMethod("v2to32").invoke(null))
		    .as("val(4294967296L) must load 4294967296; switch on low 32 bits emits LCONST_0")
		    .isEqualTo(4294967296L);
	}
	
	@Test
	void longValLow32BitsOneIsCorrupted() throws Exception{
		// -4294967295L has low 32 bits == 1 (two's complement: 0xFFFFFFFF),
		// but it is NOT 1L. LVal.emit (Insn.java:82) matches case 1 and emits
		// LCONST_1, so the generated method returns 1L instead of -4294967295L.
		var cls = generateAndLoad("reprolval.LValLow32One", cd -> {
			FunctionDefinition fn = cd.function("vNegM1").staticAcc().returns(long.class);
			fn.body()
			  .val(-4294967295L) // LVal(-4294967295L) -> emit: (int)value == 1 -> LCONST_1 (bug; must be LDC -4294967295L)
			  .returnOp();
		});
		// Bug: expected -4294967295, but the emitted LCONST_1 makes the method return 1.
		assertThat(cls.getMethod("vNegM1").invoke(null))
		    .as("val(-4294967295L) must load -4294967295; switch on low 32 bits emits LCONST_1")
		    .isEqualTo(-4294967295L);
	}
	
	@Test
	void addLongCorrupted() throws Exception{
		// Long addition routes through the same corrupting emitter: Insn.Increment
		// LONG case (Insn.java:923-926) does LVal.emit(writer, val.longValue()) then
		// LADD. Note: the DSL has no add(long) overload (only add(int)/add(double),
		// and add(double) rejects a LONG stack), so the corrupted constant is pushed
		// with val(long) and combined with .add(0) to exercise the Increment LONG path.
		// Computes 4294967296L + 0L == 0L + 4294967296L.
		var cls = generateAndLoad("reprolval.AddLong", cd -> {
			FunctionDefinition fn = cd.function("add2to32").staticAcc().returns(long.class);
			fn.body()
			  .val(4294967296L) // LVal(4294967296L) -> (int)value == 0 -> LCONST_0 (bug; must be LDC)
			  .add(0)           // Increment(LONG): LVal.emit(writer, 0L) -> LCONST_0 (correct here), LADD
			  .returnOp();
		});
		// Bug: 4294967296L + 0L is computed as 0L + 0L = 0L because the first
		// constant was truncated to LCONST_0 by the low-32-bits switch.
		assertThat(cls.getMethod("add2to32").invoke(null))
		    .as("0L + 4294967296L must be 4294967296; LVal corruption yields 0L + 0L = 0L")
		    .isEqualTo(4294967296L);
	}
	
	@Test
	void longValCorrectValueWorks() throws Exception{
		// Positive control: 1234567890123L has low 32 bits == 1912276171, which is
		// neither 0 nor 1, so LVal.emit (Insn.java:85) takes the default branch and
		// emits LDC 1234567890123L - the CORRECT path. This must pass, proving the
		// harness is sound and the LDC path works, isolating the failures above to
		// the low-32-bits 0/1 case.
		var cls = generateAndLoad("reprolval.LValCorrect", cd -> {
			FunctionDefinition fn = cd.function("vBig").staticAcc().returns(long.class);
			fn.body()
			  .val(1234567890123L) // LVal(1234567890123L) -> (int)value == 1912276171 -> LDC (correct)
			  .returnOp();
		});
		assertThat(cls.getMethod("vBig").invoke(null))
		    .as("val(1234567890123L) must load 1234567890123 via LDC (low 32 bits not 0/1)")
		    .isEqualTo(1234567890123L);
	}
	
	@Test
	void zeroAndOneLongCorrect() throws Exception{
		// Control: 0L and 1L are the INTENDED LCONST_0/LCONST_1 cases - the switch
		// on (int)value matches correctly for these exact values. These must pass
		// against the current code, showing the intended fast path is fine and only
		// non-0/1 values with low 32 bits 0/1 are corrupted.
		var cls = generateAndLoad("reprolval.LValZeroOne", cd -> {
			FunctionDefinition fn0 = cd.function("v0").staticAcc().returns(long.class);
			fn0.body()
			   .val(0L) // LVal(0L) -> (int)value == 0 -> LCONST_0 (correct)
			   .returnOp();
			FunctionDefinition fn1 = cd.function("v1").staticAcc().returns(long.class);
			fn1.body()
			   .val(1L) // LVal(1L) -> (int)value == 1 -> LCONST_1 (correct)
			   .returnOp();
		});
		assertThat(cls.getMethod("v0").invoke(null))
		    .as("val(0L) must load 0L via LCONST_0")
		    .isEqualTo(0L);
		assertThat(cls.getMethod("v1").invoke(null))
		    .as("val(1L) must load 1L via LCONST_1")
		    .isEqualTo(1L);
	}
}
