package com.lapissea.dfs.inspect.display.vk.enums;

import com.lapissea.dfs.inspect.display.VUtils;

import static org.lwjgl.vulkan.VK10.*;

public enum VkBlendFactor implements VUtils.IDValue{
	ZERO(VK_BLEND_FACTOR_ZERO),
	ONE(VK_BLEND_FACTOR_ONE),
	SRC_COLOR(VK_BLEND_FACTOR_SRC_COLOR),
	ONE_MINUS_SRC_COLOR(VK_BLEND_FACTOR_ONE_MINUS_SRC_COLOR),
	DST_COLOR(VK_BLEND_FACTOR_DST_COLOR),
	ONE_MINUS_DST_COLOR(VK_BLEND_FACTOR_ONE_MINUS_DST_COLOR),
	SRC_ALPHA(VK_BLEND_FACTOR_SRC_ALPHA),
	ONE_MINUS_SRC_ALPHA(VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA),
	DST_ALPHA(VK_BLEND_FACTOR_DST_ALPHA),
	ONE_MINUS_DST_ALPHA(VK_BLEND_FACTOR_ONE_MINUS_DST_ALPHA),
	CONSTANT_COLOR(VK_BLEND_FACTOR_CONSTANT_COLOR),
	ONE_MINUS_CONSTANT_COLOR(VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_COLOR),
	CONSTANT_ALPHA(VK_BLEND_FACTOR_CONSTANT_ALPHA),
	ONE_MINUS_CONSTANT_ALPHA(VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_ALPHA),
	SRC_ALPHA_SATURATE(VK_BLEND_FACTOR_SRC_ALPHA_SATURATE),
	SRC1_COLOR(VK_BLEND_FACTOR_SRC1_COLOR),
	ONE_MINUS_SRC1_COLOR(VK_BLEND_FACTOR_ONE_MINUS_SRC1_COLOR),
	SRC1_ALPHA(VK_BLEND_FACTOR_SRC1_ALPHA),
	ONE_MINUS_SRC1_ALPHA(VK_BLEND_FACTOR_ONE_MINUS_SRC1_ALPHA),
	;
	
	public final int id;
	VkBlendFactor(int id){ this.id = id; }
	@Override
	public int id(){ return id; }
	
	public static VkBlendFactor from(int id){ return VUtils.fromID(VkBlendFactor.class, id); }
}
